PrismarineJS/prismarine-chunk

README.md
example.js
package.json
src/chunk.js
test/test.js

Also add an api description in the readme and an example
Fix #14 and #13

Use prismarine block

---

README.md
example.js
package.json
src/index.js
src/pe/1.0/chunk.js
src/pe/1.0/subchunk.js
test/test.js

Minecraft: PE 1.0.0.0 support

---

src/pc/1.9/chunk.js

This makes it possible to do
```
column.load(args.data,args.bitMap,args.skyLightSent);
```
instead of
```
column.load(args.data,args.bitMap);
```
in PrismarineJS/mineflayer, thereby adding support for dimensions other than the overworld.
I only implemented this for pc/1.9, but since the `skyLightSent` parameter is optional, this will not break backward compatibility and support for other versions can be added easily 🎉 .

Add skyLightSent param to Chunk.load (pc/1.9)

---

src/index.js

Catch "no chunk implementation error"

Catch "no chunk implementation error"

---

README.md
package.json
src/index.js
src/pc/1.15/ChunkColumn.js
src/pc/1.15/ChunkSection.js
src/pc/1.15/chunk.js
test/test.js

Copied 1.14 chunks and made the changes for getting/setting the biome in 1.15.
load(data) no longer read the biomes, dump() no longer write the biomes.
We need to add a loadBiomes and dumpBiomes() similar to loadLight() and dumpLight()
Closes #80 #76

1.15 chunks implementation

---

src/pc/common/BitArrayNoSpan.js

It should work, unit tests are ok. To be tested with actual 1.16 chunks.

Implement BitArrayNoSpan

---

package.json
src/index.js
src/pc/1.16/ChunkColumn.js
src/pc/1.16/ChunkSection.js
src/pc/1.16/chunk.js
src/pc/common/BitArrayNoSpan.js

Fix 1.16 implementation

---

src/pc/1.13/ChunkColumn.js
src/pc/1.14/ChunkColumn.js
src/pc/1.15/ChunkColumn.js
src/pc/1.16/ChunkColumn.js
src/pc/1.8/chunk.js
src/pc/1.9/ChunkColumn.js
src/pe/0.14/chunk.js
src/pe/1.0/chunk.js
test/test.js

See https://github.com/PrismarineJS/mineflayer/issues/1153

Protect against out of bound sections

---

src/pc/1.13/ChunkColumn.js
src/pc/1.14/ChunkColumn.js
src/pc/1.15/ChunkColumn.js
src/pc/1.16/ChunkColumn.js
src/pc/1.9/ChunkColumn.js
src/pc/common/BitArray.js
src/pc/common/BitArray.test.js
src/pc/common/BitArrayNoSpan.js

we observed a speed up of x3 in firefox and x8 in chrome with these changes
with benchmark from #107

optimize for browser by inlining getSectionIndex and removing asserts

---

src/pc/common/BitArray.js
src/pc/common/BitArray.test.js
src/pc/common/BitArrayNoSpan.js

Add utility functions to convert bitarrays to or from arrays.

Add toArray/fromArray to BitArrays

---

src/pc/1.17/ChunkColumn.js
types/chunk.d.ts

I was busy rebasing this stuff when _someone_ got impatient

Add type info and bounds checks

---

src/pc/common/PaletteChunkSection.js

https://github.com/PrismarineJS/prismarine-chunk/issues/153 or even https://github.com/PrismarineJS/prismarine-chunk/issues/154 will be a better fix

expose palette in 1.18

---

src/pc/1.18/ChunkColumn.js
src/pc/common/PaletteChunkSection.js

better way at <https://github.com/PrismarineJS/prismarine-chunk/issues/154>

improve the palette hack for 1.18

---

test/test.js

@nickelpro fyi
fixes #158 
sadly this doesn't find any bug

histogram test

---

src/pc/common/PaletteChunkSection.js

Block sections are not biomes

---

types/index.d.ts

This does not help much, but at least make typings usable.

Fix compile errors in typings

---

src/pc/1.13/ChunkColumn.js
src/pc/1.8/chunk.js
src/pc/1.9/ChunkColumn.js

Fix setBlock calling setSkylight when chunk does not have skylight

---

types/section.d.ts

I left write on any because I'm not sure what type it has at the moment.
CommonChunkSection:
https://github.com/PrismarineJS/prismarine-chunk/blob/master/src/pc/common/CommonChunkSection.js

Added missing fields from CommonChunkSection

---

src/bedrock/1.18/ChunkColumn.js

See #229 for more information.

Fixes issue #229

---

src/pc/1.18/ChunkColumn.js
src/pc/common/BitArrayNoSpan.js
src/pc/common/PaletteBiome.js
src/pc/common/PaletteChunkSection.js
src/pc/common/PaletteContainer.js

added a fix that cursor proposed

1.21.5 continued
